---
# tasks file for roles/vrlcm_deploy_vra_iaas_servers

- name: Add vRA Service Account to Local Administrators Group
  win_group_membership:
    name: Administrators
    members:
      - "{{ vra_service_account }}"
    state: present

- name: Add vRA Service Account to Log on as a service
  win_user_right:
    name: SeServiceLogonRight
    users:
      - "{{ vra_service_account }}"
    action: add

- name: Add vRA Service Account to Log on as a batch job
  win_user_right:
    name: SeBatchLogonRight
    users:
      - "{{ vra_service_account }}"
    action: add

- name: Create a profile for vRA Service Account
  win_user_profile:
    username: "{{ vra_service_account }}"
    state: present