---
# tasks file for roles/vrlcm_get_auth_token

- name: Request API Authorization Token
  uri:
    url: "https://{{ inventory_hostname |lower }}/lcm/api/v{{ vrlcm_api_version }}/login"
    method: POST
    headers:
      Accept: "{{ http_Accept }}"
    validate_certs: "{{ http_validate_certs }}"
    status_code: [200]
    body_format: "{{ http_body_format }}"
    body:
      username: "{{ vrlcm_gui_username }}"
      password: "{{ vrlcm_gui_password }}"
  register: response
  run_once: true
  delegate_to: localhost
  delegate_facts: True
  no_log: true

- name: Set API Authorization Token
  set_fact:
    vrlcm_api_auth_token: "{{ response.json.token }}"
