---
# tasks file for roles/vrlcm_add_vcenter_server

- name: Include Request API Authorization Token if not defined
  include_role:
    name: vrlcm_get_auth_token
  when: vrlcm_api_auth_token is not defined or vrlcm_api_auth_token == ""
  
- name: Add vCenter Servers
  include: vrlcm_add_vcenter_server.yml
  loop: "{{ vrlcm_vcenter_servers }}"
  loop_control:
    loop_var: vcenter
