---
# tasks file for roles/vrlcm_configure_ssh

- name: Include Request API Authorization Token if not defined
  include_role:
    name: vrlcm_get_auth_token
  when: vrlcm_api_auth_token is not defined or vrlcm_api_auth_token == ""

- name: Configure SSH
  uri:
    url: "https://{{ inventory_hostname |lower }}/lcm/api/v{{ vrlcm_api_version }}/settings"
    method: POST
    headers:
      Accept: "{{ http_Accept }}"
      x-xenon-auth-token: "{{ vrlcm_api_auth_token }}"
    validate_certs: "{{ http_validate_certs }}"
    status_code: [200]
    body_format: "{{ http_body_format }}"
    body:
      sshEnabled: "{{ vrlcm_ssh_enabled }}"
      rootPassword: "{{ vrlcm_root_password }}"
      sshuserPassword: "{{ vrlcm_sshuser_password }}"
  register: response
  run_once: true
  delegate_to: localhost
  delegate_facts: true
  changed_when: response.status == 200
  no_log: true

- name: Set flag to indicate SSH password changed
  set_fact:
    ssh_password_changed: true
