---
# tasks file for roles/vrlcm_wait_for_request

- name: Include Request API Authorization Token if not defined
  include_role:
    name: vrlcm_get_auth_token
  when: vrlcm_api_auth_token is not defined or vrlcm_api_auth_token == ""

- name: Get Request
  uri:
    url: "https://{{ inventory_hostname |lower }}/lcm/api/v{{ vrlcm_api_version }}/request/status/{{ requestId }}"
    method: GET
    headers:
      Accept: "{{ http_Accept }}"
      x-xenon-auth-token: "{{ vrlcm_api_auth_token }}"
    validate_certs: "{{ http_validate_certs }}"
    status_code: [200]
  register: response
  run_once: true
  delegate_to: localhost
  delegate_facts: true
  when: requestId is defined
  until: >
    response.json.state == "COMPLETED" or 
    response.json.state == "FAILED"
  retries: 50
  delay: 10

- name: Check if Request Failed.
  fail:
    msg: "{{ response.json.retryParameters[0].message }}"
  when: response.json.state == "FAILED"
